title: 'ОЛЦ «Северный»'
default_lang: ru
author:
  name: 'Andrey Adamovich'
  email: gooddha@ya.ru
taxonomies:
  - category
  - tag
metadata:
  description: 'Оздоровительно лечебный центр-пансионат «Северный» – это один из лучших пансионатов с лечением в Крыму. Основная задача пансионата - оздоровление и санаторно-курортное лечение отдыхающих. Высшая аккредитация по медпрактике, отличная спортивная база. Отдыхающие размещаются в 4-х комфортабельных 3-х этажных спальных корпусах располагающих двухместными стандартными номерами со всеми удобствами и двухместными двухкомнатными номерами повышенной комфортности.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
phones:
  mobile: '+7 (978) 270-01-38'
  city: ''
